-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- User Settings Table
CREATE TABLE IF NOT EXISTS user_settings (
  uid TEXT PRIMARY KEY,
  persona_name TEXT DEFAULT 'Beatrice',
  user_call_name TEXT DEFAULT 'Boss',
  system_prompt TEXT DEFAULT 'How does it react? Emotionally believable, easy to talk to in live voice conversation. How does it respond? Like a person with presence, timing, texture, judgment, and conversational instinct.',
  voice TEXT DEFAULT 'Aoede',
  language TEXT DEFAULT 'English'
);

-- Enable RLS
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;

-- Add policies (if using anon key, otherwise service role bypasses)
CREATE POLICY "Users can manage their own settings" ON user_settings
  FOR ALL USING (auth.uid() = uid);

-- User Memories Table
CREATE TABLE IF NOT EXISTS user_memories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid TEXT NOT NULL,
  content TEXT NOT NULL,
  type TEXT DEFAULT 'personal',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS
ALTER TABLE user_memories ENABLE ROW LEVEL SECURITY;

-- Add policies
CREATE POLICY "Users can manage their own memories" ON user_memories
  FOR ALL USING (auth.uid() = uid);
