-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. CLEAN UP (Optional: Uncomment these if you want to start fresh)
-- DROP TABLE IF EXISTS user_memories;
-- DROP TABLE IF EXISTS user_settings;

-- 2. User Settings Table
-- We use 'uid' to store the Firebase User ID.
CREATE TABLE IF NOT EXISTS user_settings (
  uid TEXT PRIMARY KEY,
  persona_name TEXT DEFAULT 'Beatrice',
  user_call_name TEXT DEFAULT 'Boss',
  system_prompt TEXT DEFAULT 'How does it react? Emotionally believable, easy to talk to in live voice conversation. How does it respond? Like a person with presence, timing, texture, judgment, and conversational instinct.',
  voice TEXT DEFAULT 'Aoede',
  language TEXT DEFAULT 'English'
);

-- 3. User Memories Table
CREATE TABLE IF NOT EXISTS user_memories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid TEXT NOT NULL,
  content TEXT NOT NULL,
  type TEXT DEFAULT 'personal',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- NOTE ON RLS (Row Level Security):
-- Since we are using Firebase Auth on the client and the Supabase Service Role Key on the server, 
-- your server-side queries bypass RLS anyway. 
-- If you want to enable RLS for extra security (even though we filter by UID in code), use the following:

-- ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE user_memories ENABLE ROW LEVEL SECURITY;

-- If you weren't using a Service Role Key, you would need complex custom JWT mapping 
-- to make auth.uid() match Firebase IDs. For now, your server handles this security.
